#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# ///
"""Materialise `plugin/` as real files copied from the component trees it publishes.

WHY THE MIRROR EXISTS, measured on Claude Code 2.1.245 (agentic-sdlc-d0ab).  `plugin/` used to
hold five committed symlinks into `skills/`, `agents/claude/`, `commands/`, `output-styles/`, and
`workflows/`, which cost two live defects:

  * `claude plugin validate ./plugin --strict` exited 1 with one warning per component directory:
    "This directory is a symlink and nothing in it was read -- component directories are read
    without following symlinks."  Three of the five were reported; `output-styles` and `workflows`
    were not even walked, because the manifest declared no field for them.
  * A materialisation that carries ONLY the plugin subtree -- what a `github`/`archive` plugin
    source fetches, and what `git archive HEAD plugin | tar -x` reproduces exactly -- leaves all
    five links dangling, because every target escapes the plugin root.  The host then installs at
    exit 0 and reports `Skills (0)  Agents (0)`: a silent partial install, with no warning.

Two shapes were measured and refused before this one.  Manifest fields cannot point at the shared
trees: `"skills": "../skills"` draws `Path contains ".." which could be a path traversal attempt`
and exit 1.  Per-entry links inside a real component directory keep the dangling-target half,
since the targets still escape the plugin root.  Copied bytes are therefore the only shape that
fixes both halves, and the cost of copies -- a second tree that can go stale -- is what this
module and its gate rule exist to remove.

CONTRACT.

  * The five entries in `COMPONENTS` are the only paths under `plugin/` this module owns.  The
    manifest at `plugin/.claude-plugin/plugin.json` is authored, never generated, and never
    touched here.
  * Only regular files are copied.  A symlink anywhere inside a source tree is a REFUSAL, not a
    silent skip: silently skipping it is the defect class above, and following it could publish
    bytes from outside the repository.
  * Mode is git's own distinction and nothing finer: a source whose owner-execute bit is set lands
    at 0o755, every other file at 0o644.  Comparing owner-execute rather than the full mode keeps
    the verdict independent of the checkout's umask.
  * `--check` is a pure query.  It writes nothing, and reports drift as a refusal so the gate
    fails closed on a `plugin/` that no longer publishes what the source trees say.
  * `differences()` is the ONE predicate `--check`, `--write`, and `validate_bundle.py`'s
    `validate_plugin_tree` all read.  A second copy of "what belongs in plugin/" would be a
    second thing to keep in sync, which is the defect this module fixes.

Exit table.

| exit | name              | meaning                                                        |
| ---- | ----------------- | -------------------------------------------------------------- |
| 0    | EXIT_OK           | `--check` found no drift, or `--write` materialised the tree    |
| 2    | EXIT_USAGE        | argparse rejected the argv                                     |
| 3    | EXIT_REFUSAL      | `--check` found drift, or a source tree is missing/unreadable/  |
|      |                   | holds a symlink                                                |

A clean `--check` is evidence that `plugin/` publishes the reviewed component bytes.  It is not
evidence that the host accepts the plugin, and it authorizes no publication.
"""

from __future__ import annotations

import argparse
import filecmp
import os
from pathlib import Path
import shutil
import sys


#: (destination under `plugin/`, source relative to the repository root).  `agents` is the entry
#: this whole directory exists for: Claude Code discovers agents only in a plugin root's own
#: `agents/`, and this repository nests the Claude roster one level down.
COMPONENTS: tuple[tuple[str, str], ...] = (
    ("agents", "agents/claude"),
    ("commands", "commands"),
    ("output-styles", "output-styles"),
    ("skills", "skills"),
    ("workflows", "workflows"),
)
PLUGIN = "plugin"
#: Generated, gitignored trees that are never payload, spelled exactly as `validate_bundle.py`'s
#: `UNREVIEWED_TREES` spells them.  `__pycache__` is the one that matters in practice: running a
#: published script leaves bytecode beside its source, and publishing that would put unreviewed
#: generated bytes in the plugin AND make the gate's verdict depend on whether the test suite had
#: run.  They are pruned on both sides, so a stray one under `plugin/` is left alone rather than
#: reported or deleted.
UNREVIEWED_TREES = frozenset({".git", "node_modules", ".mermaid-runtime", "__pycache__"})
EXIT_OK = 0
EXIT_USAGE = 2
EXIT_REFUSAL = 3
REMEDY = "uv run --python 3.12.11 --script scripts/sync_plugin_tree.py --write"


class PluginTreeError(Exception):
    """A source tree cannot be read as a publishable component tree."""


def _mode_for(source: Path) -> int:
    return 0o755 if source.stat().st_mode & 0o100 else 0o644


def walk(directory: Path) -> tuple[dict[str, Path], list[str]]:
    """Regular files and symlinks under `directory`, keyed by POSIX path relative to it.

    `os.walk` rather than `rglob` so an unreviewed tree is PRUNED instead of merely skipped, and
    with `followlinks` left off so a link is reported by name rather than walked through.  Callers
    decide what a link means: on the source side it is a refusal, on the published side it is drift.
    """
    files: dict[str, Path] = {}
    links: list[str] = []
    for parent, directories, filenames in os.walk(directory):
        here = Path(parent)
        for name in sorted(directories):
            if (here / name).is_symlink():
                links.append((here / name).relative_to(directory).as_posix())
        directories[:] = sorted(
            name for name in directories if name not in UNREVIEWED_TREES and not (here / name).is_symlink()
        )
        for name in sorted(filenames):
            path = here / name
            inside = path.relative_to(directory).as_posix()
            if path.is_symlink():
                links.append(inside)
            elif path.is_file():
                files[inside] = path
    return files, links


def plan(root: Path) -> dict[str, Path]:
    """Map every file `plugin/` must hold to the source file it copies.

    Keys are POSIX-relative to the repository root so a caller can report them the way the gate
    and `git status` do.
    """
    planned: dict[str, Path] = {}
    for destination, relative in COMPONENTS:
        source_root = root / relative
        if source_root.is_symlink() or not source_root.is_dir():
            raise PluginTreeError(f"{relative} is not a readable directory to publish")
        files, links = walk(source_root)
        if links:
            raise PluginTreeError(
                f"{relative}/{links[0]} is a symlink; a published tree carries files only"
            )
        for inside, source in files.items():
            planned[f"{PLUGIN}/{destination}/{inside}"] = source
    return planned


def differences(root: Path) -> list[str]:
    """Every way the live `plugin/` disagrees with `plan()`, as one reportable line each."""
    planned = plan(root)
    found: list[str] = []
    for relative, source in planned.items():
        destination = root / relative
        if destination.is_symlink():
            found.append(f"{relative}: is a symlink, which no plugin host reads as a component")
        elif not destination.is_file():
            found.append(f"{relative}: missing")
        elif not filecmp.cmp(source, destination, shallow=False):
            found.append(f"{relative}: content differs from {source.relative_to(root).as_posix()}")
        elif destination.stat().st_mode & 0o100 != _mode_for(source) & 0o100:
            found.append(f"{relative}: execute bit differs from {source.relative_to(root).as_posix()}")
    for destination, _ in COMPONENTS:
        owned = root / PLUGIN / destination
        if owned.is_symlink():
            found.append(f"{PLUGIN}/{destination}: is a symlink, which no plugin host reads as a component")
            continue
        if not owned.is_dir():
            continue
        files, links = walk(owned)
        for inside in links:
            found.append(
                f"{PLUGIN}/{destination}/{inside}: is a symlink, which no plugin host reads as a component"
            )
        for inside in files:
            relative = f"{PLUGIN}/{destination}/{inside}"
            if relative not in planned:
                found.append(f"{relative}: published by no source tree")
    return sorted(set(found))


def materialise(root: Path) -> list[str]:
    """Make `plugin/`'s owned entries equal `plan()`, and return what changed."""
    planned = plan(root)
    changed: list[str] = []
    for destination, _ in COMPONENTS:
        owned = root / PLUGIN / destination
        # A symlink is unlinked rather than walked: `rmtree` through one would delete the source
        # tree it points at.
        if owned.is_symlink():
            owned.unlink()
            changed.append(f"unlinked {PLUGIN}/{destination}")
        elif owned.is_dir():
            files, links = walk(owned)
            for inside in [*links, *files]:
                relative = f"{PLUGIN}/{destination}/{inside}"
                if inside in links or relative not in planned:
                    (root / relative).unlink()
                    changed.append(f"removed {relative}")
            # Directories left empty by those removals, deepest first.  An unreviewed tree is
            # pruned by `walk`, so a `__pycache__` here keeps its parent and is left in place.
            for path in sorted(owned.rglob("*"), key=lambda entry: len(entry.parts), reverse=True):
                if path.is_dir() and not path.is_symlink() and not any(path.iterdir()):
                    path.rmdir()
    for relative, source in sorted(planned.items()):
        destination = root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.is_file() and filecmp.cmp(source, destination, shallow=False):
            os.chmod(destination, _mode_for(source))
            continue
        shutil.copyfile(source, destination)
        os.chmod(destination, _mode_for(source))
        changed.append(f"wrote {relative}")
    return changed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sync_plugin_tree.py",
        description=(
            "Check or refresh plugin/'s copies of the component trees it publishes. "
            "--check is the default and writes nothing."
        ),
    )
    action = parser.add_mutually_exclusive_group()
    action.add_argument(
        "--check",
        action="store_true",
        help="report drift and write nothing (the default action, spelled explicitly)",
    )
    action.add_argument(
        "--write",
        action="store_true",
        help="materialise plugin/ from the source trees instead of only reporting drift",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root to operate on (defaults to this script's checkout)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    root = arguments.root.resolve()
    if arguments.write:
        changed = materialise(root)
        for line in changed:
            print(line)
        print(f"plugin/ publishes {len(plan(root))} files from {len(COMPONENTS)} source trees")
        return EXIT_OK
    drift = differences(root)
    for line in drift:
        print(line, file=sys.stderr)
    if drift:
        print(f"error: plugin/ has drifted from its source trees; refresh with `{REMEDY}`", file=sys.stderr)
        return EXIT_REFUSAL
    print(f"plugin/ publishes {len(plan(root))} files from {len(COMPONENTS)} source trees")
    return EXIT_OK


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except PluginTreeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(EXIT_REFUSAL) from exc
